(()=>{
  "use strict";
  const {escapeHtml,cleanText,number,formatPercent,formatOdds,formatDate,taiwanToday,toast,fetchJson,validSession,signIn,signUp,signOut,submitCheckout}=window.DM;
  const leagues=[{code:"MLB",label:"美棒"},{code:"NPB",label:"日棒"},{code:"KBO",label:"韓棒"},{code:"CPBL",label:"中職"}];
  const teamAliases={
    "tsg hawks":"台鋼雄鷹","ctbc brothers":"中信兄弟","rakuten monkeys":"樂天桃猿","wei chuan dragons":"味全龍","fubon guardians":"富邦悍將","uni president 7 eleven lions":"統一7-ELEVEn獅",
    "lg twins":"LG雙子","hanwha eagles":"韓華鷹","kia tigers":"起亞虎","lotte giants":"樂天巨人","doosan bears":"斗山熊","samsung lions":"三星獅","ssg landers":"SSG登陸者","kiwoom heroes":"培證英雄","kt wiz":"KT巫師","nc dinos":"NC恐龍"
  };
  const state={page:"home",league:"MLB",recordLeague:"all",recordFilter:"all",date:taiwanToday(),session:null,role:"free",hasPro:false,health:null,model:null,prediction:null,games:[],records:null,billing:null,billingStatus:null};

  const q=id=>document.getElementById(id);
  const teamName=value=>{const clean=cleanText(value);return teamAliases[clean.toLowerCase()]||clean||"—"};
  const teamAbbr=team=>cleanText(team?.abbr||team?.code||team?.short_name||team?.name||"").slice(0,5).toUpperCase()||"—";
  const itemLeague=item=>String(item?.league||item?.prediction_snapshot?.league||item?.game?.league||"MLB").toUpperCase();
  const statusClass=status=>({won:"won",lost:"lost",push:"push",void:"void"}[status]||"");
  const statusLabel=status=>({won:"命中",lost:"未中",push:"走水",void:"作廢",pending:"待結算",published:"已發布",live:"進行中"}[status]||"待結算");

  function showPage(page){state.page=page;document.querySelectorAll(".page").forEach(el=>el.classList.toggle("active",el.id===`page-${page}`));document.querySelectorAll(".nav-btn").forEach(el=>el.classList.toggle("active",el.dataset.page===page));history.replaceState(null,"",`#${page}`);window.scrollTo({top:0,behavior:"smooth"});if(page==="games")loadGames();if(page==="ai")loadPrediction();if(page==="records")loadRecords();if(page==="more")loadMore()}
  function setLeague(code){state.league=code;document.querySelectorAll("[data-league]").forEach(button=>button.classList.toggle("active",button.dataset.league===code));q("homeLeagueMetric").textContent=code;if(state.page==="games")loadGames(true);else if(state.page==="records"){state.recordLeague=code;renderRecords()}else{loadPrediction(true);loadHome()}}
  function renderLeagueTabs(){document.querySelectorAll("[data-league-tabs]").forEach(container=>{const allowAll=container.dataset.allowAll==="true";container.innerHTML=`${allowAll?'<button class="tab" data-league="all">全部</button>':''}${leagues.map(item=>`<button class="tab ${(!allowAll&&item.code===state.league)||(allowAll&&item.code===state.recordLeague)?"active":""}" data-league="${item.code}">${item.code} ${item.label}</button>`).join("")}`;container.querySelectorAll("[data-league]").forEach(button=>button.addEventListener("click",()=>{if(allowAll){state.recordLeague=button.dataset.league;container.querySelectorAll(".tab").forEach(el=>el.classList.toggle("active",el===button));renderRecords()}else setLeague(button.dataset.league)}))})}

  function authHeaders(){return state.session?.access_token?{token:state.session.access_token}:{}}
  async function initializeAuth(){state.session=await validSession();if(state.session){try{const {data}=await fetchJson(`/predictions/latest?league=${state.league}`,{...authHeaders(),timeout:12000,retries:0,cacheKey:`latest-auth-${state.league}`,staleMs:300000});state.role=data?.member?.role||"free";state.hasPro=Boolean(data?.member?.has_pro_access);state.prediction=data}catch{state.role="free";state.hasPro=false}}renderAuth()}

  function renderAuth(){const logged=Boolean(state.session?.access_token);q("authFields").hidden=logged;q("authSummary").textContent=logged?`${state.session.user?.email||"會員"} · ${state.role==="admin"?"創辦人":state.hasPro?"Pro 會員":"免費會員"}`:"登入後可查看 Pro 推薦與完整紀錄。";q("authActions").innerHTML=logged?'<button class="btn" id="logoutButton" type="button">登出</button>':'<button class="btn primary" id="loginButton" type="button">登入</button><button class="btn" id="signupButton" type="button">免費註冊</button>';q("accountButton").textContent=state.role==="admin"?"嘉":state.hasPro?"P":"會員";q("adminLink").hidden=state.role!=="admin";q("authActions").querySelector("#logoutButton")?.addEventListener("click",async()=>{await signOut();state.session=null;state.role="free";state.hasPro=false;renderAuth();toast("已登出")});q("authActions").querySelector("#loginButton")?.addEventListener("click",handleLogin);q("authActions").querySelector("#signupButton")?.addEventListener("click",handleSignup)}
  async function handleLogin(){const email=q("authEmail").value.trim(),password=q("authPassword").value;if(!email||!password)return toast("請輸入 Email 與密碼");try{state.session=await signIn(email,password);toast("登入成功");await initializeAuth();await Promise.all([loadPrediction(true),loadRecords(true),loadBillingStatus()])}catch(error){toast(error.message||"登入失敗")}}
  async function handleSignup(){const email=q("authEmail").value.trim(),password=q("authPassword").value;if(!email||password.length<6)return toast("請輸入 Email，密碼至少 6 碼");try{const payload=await signUp(email,password);if(payload?.access_token){state.session=payload;await initializeAuth();toast("註冊完成")}else toast("註冊完成，請至信箱確認") }catch(error){toast(error.message||"註冊失敗")}}

  async function checkHealth(){const el=q("apiStatus");try{const {data}=await fetchJson("/health",{timeout:7000,retries:0});state.health=data;el.className="status-chip online";el.innerHTML='<span class="dot"></span><span>API 正常</span>';q("homeModelMetric").textContent=data?.model_calibration?.status==="completed"?"已校準":"已連線"}catch{el.className="status-chip warning";el.innerHTML='<span class="dot"></span><span>資料延遲</span>';q("homeModelMetric").textContent="更新延遲"}}
  async function loadModelStatus(){try{const {data,stale}=await fetchJson("/model/status",{cacheKey:"model-status",staleMs:1800000,timeout:9000,retries:1});state.model=data;renderModelStatus(stale)}catch(error){q("homeModelStatus").innerHTML=`<div class="empty"><b>模型狀態暫時無法讀取</b>${escapeHtml(error.message||"")}</div>`}}
  function renderModelStatus(stale=false){const model=state.model||{};const scopes=model.active_scopes||[];const status=model.schema==="migration_required"?"等待資料表更新":model.profiles_loaded?`已載入 ${model.profiles_loaded} 組校準模型`:"累積樣本中";const html=`<h3>V21.1 Champion／Challenger + EV</h3><div class="info-list"><div class="info-row"><span>目前狀態</span><b>${escapeHtml(status)}${stale?"（快取）":""}</b></div><div class="info-row"><span>校準方法</span><b>Regularized Platt</b></div><div class="info-row"><span>驗證方式</span><b>時間序列留出驗證</b></div><div class="info-row"><span>自動升級</span><b>${model.policy?.auto_promote?"啟用":"停用"}</b></div>${scopes.slice(0,5).map(scope=>`<div class="info-row"><span>${escapeHtml(scope.league)} · ${escapeHtml(scope.market)}</span><b>${escapeHtml(scope.version||"active")}</b></div>`).join("")}</div><div class="note" style="margin-top:13px">${escapeHtml(model.note||"校準負責機率可信度，保守 EV 負責判斷目前賠率是否值得發布。")}</div>`;q("homeModelStatus").innerHTML=html;q("moreModelStatus").innerHTML=`<div class="model-scope"><span>後端模型</span><b>V${escapeHtml(model.model_version||"21.1.0")}</b></div><div class="model-scope"><span>校準狀態</span><b>${escapeHtml(status)}</b></div><div class="model-scope"><span>目前作用域</span><b>${scopes.length}</b></div><div class="model-scope"><span>最近執行</span><b>${escapeHtml(formatDate(model.last_run))}</b></div>`}

  function renderAnnouncements(items){const section=q("announcementSection"),list=q("homeAnnouncements");if(!section||!list)return;if(!items?.length){section.hidden=true;list.innerHTML="";return}section.hidden=false;list.innerHTML=items.map(item=>{const severity=String(item.severity||"general").toLowerCase();const severityLabel={general:"一般",important:"重要",emergency:"緊急"}[severity]||"公告";return `<article class="card announcement ${escapeHtml(severity)}"><div class="announcement-head"><h3>${escapeHtml(cleanText(item.title)||"DiamondMind 公告")}</h3><span class="severity">${severityLabel}</span></div><p>${escapeHtml(cleanText(item.summary||item.body)||"")}</p></article>`}).join("")}
  async function loadAnnouncements(){try{const {data}=await fetchJson("/announcements/active?placement=home",{...authHeaders(),cacheKey:`announcements-${state.role}`,staleMs:3600000,timeout:9000,retries:0});renderAnnouncements(data?.items||[])}catch{renderAnnouncements([])}}
  async function loadHome(){await Promise.allSettled([loadPrediction(false,true),loadAnnouncements()]);if(!state.records)await loadRecords(false,true);const stats=state.records?.stats||{};q("homeDecisionsMetric").textContent=stats.won!==undefined?Number(stats.won||0)+Number(stats.lost||0):"—";q("homeHitRateMetric").textContent=stats.hit_rate==null?"—":formatPercent(stats.hit_rate)}

  function selectionResult(selection){return selection?.result?.status||selection?.status||"pending"}
  function selectionLabel(selection){return cleanText(selection?.pick?.label||selection?.pick_label||selection?.label||"尚無推薦")}
  function selectionMatchup(selection){return cleanText(selection?.matchup||`${teamName(selection?.game?.away?.name)} @ ${teamName(selection?.game?.home?.name)}`)}
  function integrityText(selection){const integrity=selection?.data_integrity||{};if(integrity.publish_safe===true)return{pass:true,text:"官方賽事、方向、機率與盤口資料已通過完整性檢查。"};const failed=Object.entries(integrity).filter(([key,value])=>key!=="publish_safe"&&!value).map(([key])=>key);return{pass:false,text:failed.length?`資料待確認：${failed.join("、")}`:"資料完整度由後端持續檢查。"}}
  function valueMeta(selection){
    const value=selection?.value||{};
    const decision=value.decision||selection?.value_decision||"unavailable";
    const labels={high_value:"高價值 +EV",candidate:"正 EV 候選",watchlist:"觀察名單",blocked_negative_ev:"-EV 禁止",manual_review:"異常待複核",unavailable:"EV 待資料"};
    return {
      value,
      decision,
      label:labels[decision]||"EV 評估",
      positive:Number(value.conservative_ev_percent??selection?.conservative_ev_percent??-999)>=0,
      conservative:value.conservative_probability??selection?.conservative_probability,
      market:value.market_fair_probability??selection?.market_fair_probability,
      breakeven:value.break_even_probability??selection?.break_even_probability,
      ev:value.conservative_ev_percent??selection?.conservative_ev_percent,
      rawEv:value.raw_ev_percent??selection?.raw_ev_percent,
      reliability:Number(value.reliability?.score??0)*100,
      fairOdds:value.conservative_fair_odds??value.fair_odds,
    };
  }
  function valueText(value){return value==null||Number.isNaN(Number(value))?"—":`${Number(value)>=0?"+":""}${Number(value).toFixed(1)}%`}
  function pickCard(selection,title="免費精選"){
    if(!selection)return'<div class="card empty"><b>尚無正式發布推薦</b>創辦人發布後會立即顯示。</div>';
    const calibration=selection.calibration||{};
    const raw=selection.raw_model_probability??calibration.raw_probability??selection.confidence;
    const calibrated=selection.model_probability??calibration.calibrated_probability??selection.confidence;
    const value=valueMeta(selection);
    const integrity=integrityText(selection);
    const result=selectionResult(selection);
    return `<div class="pick-grid"><article class="card pick-card"><div class="pick-head"><small>LATEST PUBLISHED PICK</small><span class="badge">${escapeHtml(title)}</span></div><div class="value-strip"><span class="value-badge ${value.positive?"positive":"negative"}">${escapeHtml(value.label)}</span><span>保守 EV ${valueText(value.ev)}</span></div><h2 class="pick-title">${escapeHtml(selectionLabel(selection))}</h2><div class="pick-matchup">${escapeHtml(selectionMatchup(selection))}</div><div class="pick-core"><div><small>校準後勝率</small><b class="green">${formatPercent(calibrated)}</b></div><div><small>保守勝率</small><b>${formatPercent(value.conservative)}</b></div><div><small>市場公平機率</small><b>${formatPercent(value.market)}</b></div><div><small>保守 EV</small><b class="${value.positive?"green":"red"}">${valueText(value.ev)}</b></div><div><small>損益兩平勝率</small><b>${formatPercent(value.breakeven)}</b></div><div><small>可靠度</small><b>${formatPercent(value.reliability)}</b></div><div><small>盤口／賠率</small><b>${escapeHtml(selection.pick?.line??"獨贏")} · ${formatOdds(selection.price)}</b></div><div><small>公平賠率</small><b>${value.fairOdds==null?"—":Number(value.fairOdds).toFixed(2)}</b></div><div><small>結果</small><b class="result ${statusClass(result)}">${statusLabel(result)}</b></div></div><div class="integrity ${integrity.pass?"pass":""}">${escapeHtml(integrity.text)}</div></article><aside class="side-stack"><div class="card info-card"><h3>發布資訊</h3><div class="info-list"><div class="info-row"><span>聯盟</span><b>${escapeHtml(selection.league||state.league)}</b></div><div class="info-row"><span>比賽時間</span><b>${escapeHtml(selection.display_time_taiwan||selection.time_taiwan||formatDate(selection.game_date))}</b></div><div class="info-row"><span>資料完整度</span><b>${selection.data_quality==null?"—":formatPercent(Number(selection.data_quality)*100)}</b></div><div class="info-row"><span>盤口來源</span><b>${escapeHtml(selection.odds_source?.bookmaker||selection.odds_source?.provider||"模型分析")}</b></div><div class="info-row"><span>校準來源</span><b>${escapeHtml(calibration.source||"identity")}</b></div></div></div><div class="note">+EV 是長期期望值，不代表單場一定命中；-EV 選項不會進入 Pro 自動發布。</div></aside></div>`
  }


  function flattenPro(payload){const groups=[...(payload?.moneylines||[]),...(payload?.run_lines||[]),...(payload?.totals||[]),...(payload?.parlays?.two_leg||[]),...(payload?.parlays?.three_leg||[])];return groups}
  function renderPro(payload){
    if(!state.session)return'<div class="note pro-section">登入後可查看會員權限與 Pro 推薦。</div>';
    if(!state.hasPro)return'<div class="note pro-section">目前是免費會員。升級 Pro 後可查看獨贏、讓分、大小分及串關。</div>';
    const items=flattenPro(payload);
    if(!items.length)return'<div class="note pro-section">此聯盟最近一批沒有玩法通過保守 EV 與資料品質門檻。</div>';
    return `<section class="pro-section"><div class="section-head"><div><h2>Pro 正式推薦</h2><p>只有 +EV、真實盤口且通過資料完整度檢查的內容才會顯示。</p></div></div><div class="pro-groups">${items.map(item=>{const value=valueMeta(item);const parlayEv=item.combined_conservative_ev_percent;return `<div class="card pro-card"><div class="pro-value-head"><small>${escapeHtml(String(item.market||"PRO").toUpperCase())}</small><span class="value-badge ${Number(value.ev??parlayEv??0)>=0?"positive":"negative"}">${item.legs?`串關 EV ${valueText(parlayEv)}`:`${escapeHtml(value.label)} ${valueText(value.ev)}`}</span></div><b>${escapeHtml(selectionLabel(item))}</b><p>${escapeHtml(selectionMatchup(item))}<br>${item.legs?`保守組合勝率 ${formatPercent(item.combined_conservative_probability)}`:`校準 ${formatPercent(item.model_probability??item.confidence)} · 保守 ${formatPercent(value.conservative)} · 市場 ${formatPercent(value.market)}`}</p></div>`}).join("")}</div></section>`
  }


  async function loadPrediction(force=false,homeOnly=false){const target=homeOnly?q("homePick"):q("predictionContent");if(!target)return;target.innerHTML='<div class="card empty skeleton"></div>';try{let data,stale=false;if(state.session?.access_token){({data,stale}=await fetchJson(`/predictions/latest?league=${state.league}`,{...authHeaders(),cacheKey:`latest-auth-${state.league}`,staleMs:900000,timeout:14000,retries:1}));state.role=data?.member?.role||state.role;state.hasPro=Boolean(data?.member?.has_pro_access);renderAuth()}else{({data,stale}=await fetchJson(`/predictions/top?latest=true&league=${state.league}`,{cacheKey:`latest-free-${state.league}`,staleMs:1800000,timeout:12000,retries:1}))}state.prediction=data;const selection=data?.moneyline||data?.selection||null;const html=`${stale?'<div class="note" style="margin-bottom:12px">資料更新延遲，顯示上一次成功結果。</div>':''}${pickCard(selection,`${state.league} 免費精選`)}${homeOnly?"":renderPro(data)}`;target.innerHTML=html;if(homeOnly&&q("predictionContent"))q("predictionContent").innerHTML=html}catch(error){target.innerHTML=`<div class="card empty"><b>資料更新延遲</b>${escapeHtml(error.message||"暫時無法讀取推薦")}</div>`}}

  function gameStatus(game){const raw=String(game.status||game.state||game.status_code||"").toLowerCase();const awayScore=number(game.away_score??game.away?.score),homeScore=number(game.home_score??game.home?.score);const complete=awayScore!==null&&homeScore!==null;if(/final|finished|ended|completed|已結束|終了/.test(raw)&&complete)return{label:"已結束",class:"final"};if(/live|progress|進行/.test(raw))return{label:"進行中",class:"live"};if(/final|finished|ended|completed|已結束|終了/.test(raw)&&!complete)return{label:"賽果同步中",class:"live"};return{label:"未開賽",class:""}}
  function renderGames(){const list=q("gamesList");if(!state.games.length){list.innerHTML='<div class="card empty"><b>此日期沒有賽事</b>請切換日期或稍後重新整理。</div>';return}list.innerHTML=state.games.map(game=>{const status=gameStatus(game);const away=game.away||{},home=game.home||{};const awayScore=number(game.away_score??away.score),homeScore=number(game.home_score??home.score);const gameId=game.game_pk??game.id??game.event_id??"";return `<button class="card game-card" type="button" data-game-id="${escapeHtml(gameId)}"><div class="game-time"><b>${escapeHtml(game.display_time_taiwan||game.time_taiwan||"—")}</b><small>${escapeHtml(cleanText(game.venue)||state.league)}</small></div><div class="teams"><div class="team"><strong>${escapeHtml(teamAbbr(away))}</strong><span>${escapeHtml(teamName(away.name))}</span><em>${awayScore??""}</em></div><div class="team"><strong>${escapeHtml(teamAbbr(home))}</strong><span>${escapeHtml(teamName(home.name))}</span><em>${homeScore??""}</em></div></div><span class="status ${status.class}">${status.label}</span></button>`}).join("");list.querySelectorAll("[data-game-id]").forEach(button=>button.addEventListener("click",()=>loadGameDetail(button.dataset.gameId)))}
  function detailGame(payload){return payload?.game||payload?.game_info||payload||{}}
  function detailText(payload){const analysis=payload?.analysis||payload?.ai_analysis||payload?.model_analysis||payload?.summary||payload?.prediction?.analysis;return cleanText(typeof analysis==="string"?analysis:analysis?.summary||analysis?.text||analysis?.recommendation||"")}
  async function loadGameDetail(gameId){if(!gameId)return toast("此場賽事缺少官方編號");const dialog=q("gameDialog"),content=q("gameDetailContent");content.innerHTML='<div class="empty skeleton"></div>';if(typeof dialog.showModal==="function")dialog.showModal();else dialog.setAttribute("open","");try{const {data,stale}=await fetchJson(`/${state.league.toLowerCase()}/games/${encodeURIComponent(gameId)}`,{...authHeaders(),cacheKey:`game-detail-${state.league}-${gameId}`,staleMs:1800000,timeout:16000,retries:1});const game=detailGame(data),away=game.away||data?.away||{},home=game.home||data?.home||{};const awayScore=number(game.away_score??away.score),homeScore=number(game.home_score??home.score);q("gameDialogTitle").textContent=`${teamName(away.name)} @ ${teamName(home.name)}`;const locked=Boolean(data?.analysis_locked||data?.access?.has_pro_access===false);const analysis=detailText(data);const meta=[['比賽時間',game.display_time_taiwan||game.time_taiwan||game.game_time||'—'],['球場',cleanText(game.venue)||'—'],['客隊先發',cleanText(game.away_pitcher||away.probable_pitcher?.name||away.pitcher)||'尚未公布'],['主隊先發',cleanText(game.home_pitcher||home.probable_pitcher?.name||home.pitcher)||'尚未公布']];content.innerHTML=`${stale?'<div class="note" style="margin-bottom:12px">資料更新延遲，顯示上次賽事詳情。</div>':''}<div class="card info-card"><div class="detail-score"><b>${escapeHtml(teamName(away.name))}</b><strong>${awayScore??'—'}</strong></div><div class="detail-score"><b>${escapeHtml(teamName(home.name))}</b><strong>${homeScore??'—'}</strong></div><div class="detail-grid">${meta.map(([label,value])=>`<div class="detail-item"><small>${label}</small><b>${escapeHtml(value)}</b></div>`).join('')}</div>${locked?'<div class="detail-analysis">完整 AI 賽事分析為 Pro 會員功能；官方賽程與比分仍保持公開。</div>':analysis?`<div class="detail-analysis">${escapeHtml(analysis)}</div>`:'<div class="detail-analysis">賽事資料已載入；模型分析會在資料完整度達標後顯示。</div>'}</div>`}catch(error){content.innerHTML=`<div class="empty"><b>賽事詳情暫時無法更新</b>${escapeHtml(error.message||"")}</div>`}}
  async function loadGames(force=false){q("gamesList").innerHTML='<div class="card empty skeleton"></div>';q("gamesQuality").innerHTML="";try{const [{data,stale},{data:quality}]=await Promise.all([fetchJson(`/games?league=${state.league}&date=${state.date}`,{cacheKey:`games-${state.league}-${state.date}`,staleMs:3600000,timeout:15000,retries:1}),fetchJson(`/system/data-quality?league=${state.league}&date=${state.date}`,{cacheKey:`quality-${state.league}-${state.date}`,staleMs:3600000,timeout:15000,retries:0}).catch(()=>({data:null}))]);state.games=data?.items||[];renderGames();const meta=data?.meta||{};q("gamesQuality").innerHTML=`<span class="${stale?"warn":"pass"}">${stale?"備援快取":"官方資料"}</span><span>已載入 ${state.games.length} 場</span>${quality?`<span class="${quality.status==="pass"?"pass":"warn"}">完整度 ${quality.quality_score==null?"—":Math.round(quality.quality_score*100)+"%"}</span>`:""}${meta.parser_status?`<span>解析 ${escapeHtml(meta.parser_status)}</span>`:""}` }catch(error){q("gamesList").innerHTML=`<div class="card empty"><b>賽程暫時無法更新</b>${escapeHtml(error.message||"")}</div>`}}

  function flattenRecords(payload){const rows=[];(payload?.items||[]).forEach(record=>{const snap=record.prediction_snapshot||{};rows.push({date:record.recommendation_date||snap.target_date,league:itemLeague(record),market:snap.market||"moneyline",label:selectionLabel(snap),matchup:selectionMatchup(snap),status:record.status||snap.result?.status||"pending",score:[record.away_score,record.home_score].every(v=>v!=null)?`${record.away_score}:${record.home_score}`:""})});(payload?.market_packages||[]).forEach(pkg=>{const date=pkg.recommendation_date||pkg.publication?.target_date;[...(pkg.moneylines||[]),...(pkg.run_lines||[]),...(pkg.totals||[]),...(pkg.parlays?.two_leg||[]),...(pkg.parlays?.three_leg||[])].forEach(item=>rows.push({date,league:itemLeague(item),market:item.market||"pro",label:selectionLabel(item),matchup:selectionMatchup(item),status:item.result?.status||item.status||"pending",score:item.result?.away_score!=null?`${item.result.away_score}:${item.result.home_score}`:""}))});return rows.sort((a,b)=>String(b.date||"").localeCompare(String(a.date||"")))}
  function renderRecords(){const payload=state.records||{};const stats=payload.stats||{};q("recordsDecisions").textContent=Number(stats.won||0)+Number(stats.lost||0);q("recordsWins").textContent=stats.won??"—";q("recordsLosses").textContent=stats.lost??"—";q("recordsHitRate").textContent=stats.hit_rate==null?"—":formatPercent(stats.hit_rate);let rows=flattenRecords(payload);if(state.recordLeague!=="all")rows=rows.filter(row=>row.league===state.recordLeague);if(state.recordFilter!=="all")rows=rows.filter(row=>row.status===state.recordFilter);q("recordList").innerHTML=rows.length?rows.slice(0,160).map(row=>`<div class="record"><small>${escapeHtml(row.date||"—")}</small><span class="record-market">${escapeHtml(String(row.market).toUpperCase())}</span><div class="record-main"><b>${escapeHtml(row.label)}</b><span>${escapeHtml(row.league)} · ${escapeHtml(row.matchup)} ${row.score?`· ${escapeHtml(row.score)}`:""}</span></div><span class="result ${statusClass(row.status)}">${statusLabel(row.status)}</span></div>`).join(""):'<div class="empty"><b>目前沒有符合的紀錄</b>切換聯盟或狀態查看。</div>'}
  async function loadRecords(force=false,silent=false){if(!silent)q("recordList").innerHTML='<div class="empty skeleton"></div>';try{const {data,stale}=await fetchJson("/records",{...authHeaders(),cacheKey:`records-${state.hasPro?"pro":"free"}`,staleMs:1800000,timeout:16000,retries:1});state.records=data;state.role=data?.member?.role||state.role;state.hasPro=Boolean(data?.member?.has_pro_access);renderAuth();renderRecords();if(stale&&!silent)toast("紀錄更新延遲，顯示上次資料")}catch(error){if(!silent)q("recordList").innerHTML=`<div class="empty"><b>紀錄暫時無法更新</b>${escapeHtml(error.message||"")}</div>`}}

  async function loadBillingConfig(){try{const {data}=await fetchJson("/billing/config",{cacheKey:"billing-config",staleMs:86400000,timeout:9000,retries:1});state.billing=data;q("billingSummary").textContent=data.enabled?`${data.provider} ${data.live?"正式":"測試"}環境 · 固定期限方案`:"付款服務尚未正式啟用";q("planGrid").innerHTML=(data.plans||[]).map(plan=>`<div class="plan"><b>${escapeHtml(plan.name)}</b><strong>NT$ ${Number(plan.amount).toLocaleString("zh-TW")}</strong><button class="btn primary" data-plan="${escapeHtml(plan.code)}" type="button" style="margin-top:11px;width:100%">選擇</button></div>`).join("");q("planGrid").querySelectorAll("[data-plan]").forEach(button=>button.addEventListener("click",()=>checkout(button.dataset.plan)))}catch(error){q("billingSummary").textContent=error.message||"方案暫時無法讀取"}}
  async function loadBillingStatus(){if(!state.session){state.billingStatus=null;return}try{const {data}=await fetchJson("/billing/status",{...authHeaders(),timeout:10000,retries:1});state.billingStatus=data;q("billingSummary").textContent=data.active?`目前方案：${data.plan||data.status} · ${data.current_period_end?`到期 ${formatDate(data.current_period_end)}`:"完整權限"}`:(state.billing?.enabled?"目前為免費會員，可選擇 Pro 方案。":"付款服務尚未啟用")}catch(error){toast(error.message||"無法更新會員狀態")}}
  async function checkout(plan){if(!state.session)return toast("請先登入會員");try{const {data}=await fetchJson("/billing/checkout",{method:"POST",body:{plan},...authHeaders(),timeout:16000,retries:0});submitCheckout(data)}catch(error){toast(error.message||"付款頁建立失敗")}}
  async function claimTrial(){if(!state.session)return toast("請先登入會員");try{const {data}=await fetchJson("/membership/trial/claim",{method:"POST",body:{},...authHeaders(),timeout:15000,retries:0});toast(data.message||"試用已啟用");await initializeAuth();await loadBillingStatus()}catch(error){toast(error.message||"無法領取試用")}}
  async function loadMore(){if(!state.billing)await loadBillingConfig();await loadBillingStatus();if(!state.model)await loadModelStatus()}

  function closeGameDialog(){const dialog=q("gameDialog");if(typeof dialog.close==="function"&&dialog.open)dialog.close();else dialog.removeAttribute("open")}
  function bind(){document.querySelectorAll("[data-page]").forEach(button=>button.addEventListener("click",()=>showPage(button.dataset.page)));q("accountButton").addEventListener("click",()=>showPage("more"));q("homeRefresh").addEventListener("click",()=>loadHome());q("predictionRefresh").addEventListener("click",()=>loadPrediction(true));q("gamesRefresh").addEventListener("click",()=>loadGames(true));q("recordsRefresh").addEventListener("click",()=>loadRecords(true));q("gameDialogClose").addEventListener("click",closeGameDialog);q("gameDialog").addEventListener("click",event=>{if(event.target===q("gameDialog"))closeGameDialog()});q("gamesDate").value=state.date;q("gamesDate").addEventListener("change",event=>{state.date=event.target.value||taiwanToday();loadGames(true)});q("recordFilters").querySelectorAll("[data-record-filter]").forEach(button=>button.addEventListener("click",()=>{state.recordFilter=button.dataset.recordFilter;q("recordFilters").querySelectorAll(".filter").forEach(el=>el.classList.toggle("active",el===button));renderRecords()}));q("trialButton").addEventListener("click",claimTrial);q("billingStatusButton").addEventListener("click",loadBillingStatus)}

  async function init(){renderLeagueTabs();bind();const hash=location.hash.replace("#","");if(["home","games","ai","records","more"].includes(hash))showPage(hash);await initializeAuth();await Promise.allSettled([checkHealth(),loadModelStatus(),loadBillingConfig(),loadHome()]);setInterval(checkHealth,180000)}
  init();
})();
